
name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: echo "::set-env name=SHORT_SHA::${GITHUB_SHA::8}"
      - run: echo "::set-env name=FILE::deploy/$SHORT_SHA.web.js"
      - run: echo "::set-env name=FILE_URL::https://raw.githubusercontent.com/mallonenogueira/teste-deployer/${GITHUB_REF##*/}/deploy/$SHORT_SHA.web.js"
    
      - run: |
          case "${GITHUB_REF##*/}" in
            "master") echo "::set-env name=URL_ENV::prod" ;;
            *) echo "::set-env name=URL_ENV::dev" ;;
          esac
          
        
      - run: |
          cat web.js > $FILE
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated - $SHORT_SHA"
          git push
      
      - name: Fetch import-map-deployer
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: 'https://import-map-deployer-mallone.herokuapp.com/services?env=${{ env.URL_ENV }}'
          CONFIGURATION: '{ "method": ${{ env.method }}, "headers": ${{ env.headers }}, "body": ${{ env.body }}}'
        env:
          method: '"PATCH"'
          headers: '{ "content-type": "application/json", "authorization": "${{ secrets.AUTHORIZATION }}" }'
          body:  '{ "service": "my-service", "url": "${{ env.FILE_URL }}" }'

      
