
name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: echo "::set-env name=SHORT_SHA::${GITHUB_SHA::8}"
      - run: echo "::set-env name=FILE::deploy/$SHORT_SHA.web.js"
      - run: echo "::set-env name=URL_ENV::deploy/$SHORT_SHA.web.js"
      
      - run: |
          IF [$GITHUB_REF === refs/head/develop]
            echo "::set-env name=URL_ENV::dev"
          ELSE
            echo "::set-env name=URL_ENV::prod"
          FI
          
      - run: echo "::set-env name=FILE_URL::https://raw.githubusercontent.com/mallonenogueira/teste-deployer/master/deploy/$SHORT_SHA.web.js?env=$URL_ENV"
        
      - run: |
          cat web.js > $FILE
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated - $SHORT_SHA"
          git push
      
      - name: Fetch import-map-deployer 📦
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://import-map-deployer-mallone.herokuapp.com/services
          CONFIGURATION: '{ "method": ${{ env.method }}, "headers": ${{ env.headers }}, "body": ${{ env.body }}}'
        env:
          method: '"PATCH"'
          headers: '{ "content-type": "application/json" }'
          body:  '{ "service": "my-service", "url": "${{ env.FILE_URL }}" }'

      
