
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - run: |
          cat web.js > deploy/${GITHUB_SHA::8}.web.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
      
      - run: |
          SRC_URL="https://raw.githubusercontent.com/mallonenogueira/teste-deployer/master/deploy/${GITHUB_SHA::8}.web.js" 
          curl --request PATCH \
          --url https://import-map-deployer-mallone.herokuapp.com/services \
          --header 'content-type: application/json' \
          --data '{
              "service": "my-service",
              "url": "${SRC_URL}"
            }'
      
